import type { Metadata } from 'next'
import './globals.css'
import Navbar from './ui/components/Navbar'
import StoreProvider from '../redux/StoreProvider'

export const metadata: Metadata = {
  title: 'CarInsurance',
  description: 'Generated by Eduardo Hernandez'
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={`max-w-screen-2xl mx-auto`}>
          <Navbar />
            {children}
        </body>
      </StoreProvider>
    </html>
  )
}
